### ISSUE TITLE
"ERROR: uninitialized constant Gem::VersionOption"

### ISSUE THREAD

**Issue by erikj** [defunkt/gem-man#1]
I installed gem-man via gem install gem-man w/ gem 1.3.5 in ruby 1.8 and ruby 1.9.1, and receive this error in both for gem-man commands. am I missing a dependency? OS is ubuntu-server karmic.

$ gem1.8 man gem-man
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::VersionOption

$ gem1.9.1 man gem-man
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::VersionOption

this seems like a useful gem, thanks for sharing.

**Comment by defunkt** [comment]
Can you try this:

```
RUBYOPT="-rrubygems/version_option" gem man gem-man
```

**Comment by defunkt** [comment]
Also, I just pushed out `0.1.2` which may fix the problem but I'm not sure. Lemme know.

**Comment by erikj** [comment]
both of those worked, thanks!
